"""change_user

Revision ID: 953de8b7e9c5
Revises: b124b4bf446f
Create Date: 2025-08-06 00:54:01.887309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '953de8b7e9c5'
down_revision: Union[str, Sequence[str], None] = 'b124b4bf446f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=60), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('access_token', sa.String(length=355), nullable=False))
    op.drop_constraint(op.f('users_id_tg_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'invite_date')
    op.drop_column('users', 'is_leaved')
    op.drop_column('users', 'id_tg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_tg', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_leaved', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('invite_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_id_tg_key'), 'users', ['id_tg'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'access_token')
    op.drop_column('users', 'password')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
